version: AppVeyor Gemstone COMTRADE Build {build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Release
environment:
  SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
before_build:
- cmd: >-
    choco install sandcastle

    nuget restore src\Gemstone.COMTRADE.sln
build:
  parallel: true
  verbosity: minimal
